---
# tasks file for roles/webservers

- name: update all packages to the latest versions
  apt: name=* state=latest

- name: install apache webserver
  apt: name=apache2 state=present

- name: delete original index.html file
  file: "path={{ index_path }} state=absent"

- name: Create a directory for github to use
  file: 
    path: /var/www/github
    state: directory

- name: download git hub repository
  git:
    repo: 'https://github.com/ajesha007/Ansible101.git'
    dest: /var/www/github
    accept_hostkey: yes
    force: yes

- name: copy index.html to the /var/www/html folder
  command: mv /var/www/github/index.html /var/www/html

- name: replace 'HOSTNAME' with that devices IP address
  replace:
    path: "{{ index_path }}"
    regexp: 'HOSTADDRESS'
    replace: '{{ ansible_all_ipv4_addresses[0] }}'
  notify: start apache
